# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: fanuc_arm
  joint_model_group_pose: zeroes
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - finger_joint1
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

finger_joint1_controller:
  type: position_controllers/JointPositionController
  joint: finger_joint1
  pid: {p: 100.0, i: 0.01, d: 10.0}

finger_joint2_controller:
  type: position_controllers/JointPositionController
  joint: finger_joint2
  pid: {p: 100.0, i: 0.01, d: 10.0}

fanuc_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  state_publish_rate: 100

controller_list:
  - name: fanuc_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
